import 'package:flutter/material.dart';
import 'package:speech_to_text/speech_to_text.dart';

class EntryScreen extends StatefulWidget {
  const EntryScreen({super.key});

    @override
      State<EntryScreen> createState() => _EntryScreenState();
      }

      class _EntryScreenState extends State<EntryScreen> {
        final titleController = TextEditingController();
          final contentController = TextEditingController();

            final SpeechToText speech = SpeechToText();

              bool listening = false;

                Future<void> startListening() async {
                    bool available = await speech.initialize();

                        if (available) {
                              setState(() => listening = true);

                                    speech.listen(
                                            onResult: (result) {
                                                      setState(() {
                                                                  contentController.text = result.recognizedWords;
                                                                            });
                                                                                    },
                                                                                          );
                                                                                              }
                                                                                                }

                                                                                                  void stopListening() {
                                                                                                      speech.stop();
                                                                                                          setState(() => listening = false);
                                                                                                            }

                                                                                                              @override
                                                                                                                Widget build(BuildContext context) {
                                                                                                                    return Scaffold(
                                                                                                                          appBar: AppBar(
                                                                                                                                  title: const Text('New Entry'),
                                                                                                                                        ),
                                                                                                                                              body: Padding(
                                                                                                                                                      padding: const EdgeInsets.all(16),
                                                                                                                                                              child: Column(
                                                                                                                                                                        children: [
                                                                                                                                                                                    TextField(
                                                                                                                                                                                                  controller: titleController,
                                                                                                                                                                                                                decoration: const InputDecoration(
                                                                                                                                                                                                                                labelText: 'Title',
                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                      const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                  Expanded(
                                                                                                                                                                                                                                                                                                child: TextField(
                                                                                                                                                                                                                                                                                                                controller: contentController,
                                                                                                                                                                                                                                                                                                                                maxLines: null,
                                                                                                                                                                                                                                                                                                                                                expands: true,
                                                                                                                                                                                                                                                                                                                                                                decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                  labelText: 'Journal Entry',
                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            listening ? Icons.mic_off : Icons.mic,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      listening
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? stopListening()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : startListening();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }