import 'package:flutter/material.dart';
import 'package:speech_to_text/speech_to_text.dart';

import '../models/journal_entry.dart';
import '../services/entry_service.dart';

class EntryScreen extends StatefulWidget {
  final JournalEntry? existingEntry;

    const EntryScreen({
        super.key,
            this.existingEntry,
              });

                @override
                  State<EntryScreen> createState() => _EntryScreenState();
                  }

                  class _EntryScreenState extends State<EntryScreen> {
                    final titleController = TextEditingController();
                      final contentController = TextEditingController();

                        final SpeechToText speech = SpeechToText();

                          final EntryService entryService = EntryService();

                            bool listening = false;

                              @override
                                void initState() {
                                    super.initState();

                                        if (widget.existingEntry != null) {
                                              titleController.text = widget.existingEntry!.title;
                                                    contentController.text = widget.existingEntry!.content;
                                                        }
                                                          }

                                                            Future<void> saveEntry() async {
                                                                if (titleController.text.isEmpty &&
                                                                        contentController.text.isEmpty) {
                                                                              return;
                                                                                  }

                                                                                      if (widget.existingEntry == null) {
                                                                                            await entryService.createEntry(
                                                                                                    JournalEntry(
                                                                                                              title: titleController.text,
                                                                                                                        content: contentController.text,
                                                                                                                                  imagePath: null,
                                                                                                                                            createdAt: DateTime.now(),
                                                                                                                                                    ),
                                                                                                                                                          );
                                                                                                                                                              } else {
                                                                                                                                                                    await entryService.updateEntry(
                                                                                                                                                                            JournalEntry(
                                                                                                                                                                                      id: widget.existingEntry!.id,
                                                                                                                                                                                                title: titleController.text,
                                                                                                                                                                                                          content: contentController.text,
                                                                                                                                                                                                                    imagePath: widget.existingEntry!.imagePath,
                                                                                                                                                                                                                              createdAt: widget.existingEntry!.createdAt,
                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                    if (mounted) {
                                                                                                                                                                                                                                                          Navigator.pop(context);
                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                  Future<void> startListening() async {
                                                                                                                                                                                                                                                                      bool available = await speech.initialize();

                                                                                                                                                                                                                                                                          if (available) {
                                                                                                                                                                                                                                                                                setState(() => listening = true);

                                                                                                                                                                                                                                                                                      speech.listen(
                                                                                                                                                                                                                                                                                              onResult: (result) {
                                                                                                                                                                                                                                                                                                        contentController.text = result.recognizedWords;
                                                                                                                                                                                                                                                                                                                  setState(() {});
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                        void stopListening() {
                                                                                                                                                                                                                                                                                                                                            speech.stop();

                                                                                                                                                                                                                                                                                                                                                setState(() {
                                                                                                                                                                                                                                                                                                                                                      listening = false;
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                              @override
                                                                                                                                                                                                                                                                                                                                                                Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                    return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                          appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                  title: const Text('Journal Entry'),
                                                                                                                                                                                                                                                                                                                                                                                          actions: [
                                                                                                                                                                                                                                                                                                                                                                                                    IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                icon: const Icon(Icons.save),
                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: saveEntry,
                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          body: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              controller: titleController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            labelText: 'Title',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            controller: contentController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            maxLines: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expands: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              labelText: 'Write your thoughts...',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        listening ? Icons.mic_off : Icons.mic,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  listening
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? stopListening()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : startListening();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }