import 'package:flutter/material.dart';

import '../models/journal_entry.dart';
import '../services/entry_service.dart';
import '../widgets/journal_card.dart';
import 'entry_screen.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

    @override
      State<HomeScreen> createState() => _HomeScreenState();
      }

      class _HomeScreenState extends State<HomeScreen> {
        final EntryService _entryService = EntryService();

          List<JournalEntry> entries = [];

            @override
              void initState() {
                  super.initState();
                      loadEntries();
                        }

                          Future<void> loadEntries() async {
                              final result = await _entryService.getEntries();

                                  setState(() {
                                        entries = result;
                                            });
                                              }

                                                Future<void> deleteEntry(int id) async {
                                                    await _entryService.deleteEntry(id);
                                                        await loadEntries();
                                                          }

                                                            @override
                                                              Widget build(BuildContext context) {
                                                                  return Scaffold(
                                                                        appBar: AppBar(
                                                                                title: const Text('JournalFlow'),
                                                                                      ),
                                                                                            body: entries.isEmpty
                                                                                                      ? const Center(
                                                                                                                    child: Text('No journal entries yet'),
                                                                                                                                )
                                                                                                                                          : ListView.builder(
                                                                                                                                                        itemCount: entries.length,
                                                                                                                                                                      itemBuilder: (context, index) {
                                                                                                                                                                                      final entry = entries[index];

                                                                                                                                                                                                      return Dismissible(
                                                                                                                                                                                                                        key: Key(entry.id.toString()),
                                                                                                                                                                                                                                          background: Container(color: Colors.red),
                                                                                                                                                                                                                                                            onDismissed: (_) {
                                                                                                                                                                                                                                                                                deleteEntry(entry.id!);
                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                    child: JournalCard(
                                                                                                                                                                                                                                                                                                                                        entry: entry,
                                                                                                                                                                                                                                                                                                                                                            onTap: () async {
                                                                                                                                                                                                                                                                                                                                                                                  await Navigator.push(
                                                                                                                                                                                                                                                                                                                                                                                                          context,
                                                                                                                                                                                                                                                                                                                                                                                                                                  MaterialPageRoute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            builder: (_) => EntryScreen(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        existingEntry: entry,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      loadEntries();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: const Icon(Icons.add),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await Navigator.push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  context,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              MaterialPageRoute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            builder: (_) => const EntryScreen(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loadEntries();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }